#!/usr/bin/env php
<?php

if(file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('NukaCode Laravel Installer', '2.1.3');
$app->add(new Laravel\Installer\Console\NewCommand);
$app->add(new Laravel\Installer\Console\DownloadCommand);

$app->run();
